---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pons6262/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH